= Parameters

The parent key for all of the following parameters is `nextcloud`.

== `namespace`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
annotations: {}
labels: {}
name: app-${_instance}
----

The namespace in which to deploy this component.


== `config`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
url: nextcloud.local <1>
tls: <2>
  enabled: true
  issuer: letsencrypt-production
persistence: <3>
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: ''
  size: 10Gi
extra: <4>
  language.config.php: |-
    <?php
    $CONFIG = [
      'default_language' => 'de',
      'default_locale' => 'de_CH',
      'default_phone_region' => 'CH',
      'default_timezone' => 'Europe/Zurich',
    ];
  proxy.config.php: |-
    <?php
    $CONFIG = array (
      'trusted_proxies' =>
      array (
        0 => '127.0.0.1',
        1 => '10.128.0.0/14',
      ),
      'forwarded_for_headers' =>
      array (
        0 => 'HTTP_X_FORWARDED_FOR',
      ),
    );
----
<1> Configure nextcloud URL.
<2> Configure tls with cert-manager.
<3> Configure persistence for nextcloud.
<4> Additional configuration files.


== `secrets`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
postgresql: '?{vaultkv:${cluster:tenant}/${cluster:name}/nextcloud/${_instance}/postgresql}'
redis: '?{vaultkv:${cluster:tenant}/${cluster:name}/nextcloud/${_instance}/redis}'
nextcloud: '?{vaultkv:${cluster:tenant}/${cluster:name}/nextcloud/${_instance}/nextcloud}'
token: '?{vaultkv:${cluster:tenant}/${cluster:name}/nextcloud/${_instance}/token}'
----

See https://syn.tools/commodore/reference/concepts.html#_secret_references[ProjectSyn Documentation] for reference.


== `database`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: true <1>
mode: standalone <2>
persistence: <3>
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: ''
  size: 5Gi
----
<1> Enable external postgresql database.
<2> Configure postgresql mode.
<3> Configure persistence for postgresql.

Enable/configure postgresql as database backend.


== `redis`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: true <1>
mode: standalone <2>
persistence: <3>
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: ''
  size: 1Gi
----
<1> Enable redis for file locking.
<2> Configure redis mode.
<3> Configure persistence for redis.

NOTE: Currently only standalone mode supported!

== `helmValues`

[horizontal]
type:: dictionary
default:: https://github.com/tegridy-io/component-nextcloud/blob/master/class/defaults.yml[See `class/defaults.yml`]

The Helm values to use when rendering the Helm charts.


== Example

[source,yaml]
----
nextcloud:
  database:
    persistence:
      storageClass: ceph-block

  config:
    url: nextcloud.apps.tegridy.io
    persistence:
      accessMode: ReadWriteMany
      storageClass: ceph-file
      size: 100Gi
----
